spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: #secret key here

            clientSecret: #secret key here

          google:
            clientId: #secret key here

            clientSecret: #secret key here

